baseURL: 'https://nimgroup.github.io/'
title: Neuroimage Intelligence Mapping Group（NIMG）
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: About
      url: about/
      weight: 1
    - name: Research
      url: research/
      weight: 2
    - name: Publication
      url: publications/
      weight: 3
    - name: Member
      url: members/
      weight: 4
    - name: Photos
      url: photos/
      weight: 5
    - name: Source
      url: source/
      weight: 6
    - name: News
      url: news/
      weight: 7
    - name: Contact
      url: contact/
      weight: 8

params:
  description: 'NIMG researches AI and machine learning for intelligent medicine, with a focus on neural navigation and image-enabled brain-computer interfaces.'
  author: NIMG
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: 'January 2006'
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ['publications', 'research', 'source', 'news']
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: NIMG
    subtitle: '我们面向脑科学、智能医学与脑机接口的交叉前沿，发展计算神经影像、脑连接组分析、影像驱动脑机接口、精准神经导航、人脑数字孪生与 AI for Health 等核心技术，探索从脑结构、脑功能、脑网络到临床诊疗决策的智能映射机制。NIMG 不追求简单堆模型、刷榜或内卷式科研，而是关注真实科学问题、可解释方法、可复现系统与临床转化价值。我们希望把每一个研究想法做成可发表的论文、可运行的代码、可演示的系统和可持续扩展的工具。这里欢迎有好奇心、有创造力、有工程能力、愿意从 0 到 1 解决问题的研究生、博士后和青年合作者加入，一起推动 AI 从“处理医学图像”走向“理解大脑、连接智能、服务健康”。'
    imageUrl: 'logo.png'
    imageWidth: 160
    imageHeight: 115
    buttons:
      - name: About
        url: about/
      - name: Research
        url: research/
      - name: Publication
        url: publications/
      - name: Member
        url: members/
      - name: Photos
        url: photos/
      - name: Source
        url: source/
      - name: News
        url: news/
      - name: Contact
        url: contact/

  socialIcons:
    #- name: CV
    #  url: cv.pdf
    - name: Email
      url: mailto:dr.yewu@outlook.com
    #- name: Zoom
    #  url: https://www.zoom.us/my/igelfeld
    - name: Location
      url: location/
    - name: Office Hours
      url: officehours/
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=soMcNA8AAAAJ
    - name: GitHub
      url: https://github.com/nimgroup
    #- name: Substack
    #  url: https://pmichaillat.substack.com
    #- name: YouTube
    #  url: https://www.youtube.com/@pmichaillat
    - name: Twitter
      url: https://x.com/wuye4567
    #- name: Bluesky
    #  url: https://bsky.app/profile/pmichaillat.bsky.social
    - name: ORCID
      url: https://orcid.org/0000-0002-8643-4023

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: 'NIMG'
    icon: logo.png
    iconHeight: 40
    iconWidth: 56

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
